# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artykuly_bhp', '0002_przydzial_who'),
        ('pracownicy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('braki_magazynowe', models.ManyToManyField(to='artykuly_bhp.produkty')),
                ('nadchodzace_szkolenia', models.ManyToManyField(to='pracownicy.Worker')),
            ],
        ),
    ]
