# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pracownicy', '0004_auto_20170131_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='produkty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('count', models.PositiveIntegerField()),
                ('exp_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='przydzial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField(auto_now_add=True)),
                ('what', models.ManyToManyField(to='artykuly_bhp.produkty')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pracownicy.Worker')),
            ],
        ),
    ]
