# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0001_initial'),
        ('artykuly_bhp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='przydzial',
            name='who',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pracownicy.Worker'),
            preserve_default=False,
        ),
    ]
