# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 10:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('szkolenia', '0005_auto_20170130_2224'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_instruction', models.DateField()),
                ('next_instruction', models.DateField()),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szkolenia.instruction')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Surname', models.CharField(max_length=30)),
                ('PESEL', models.CharField(max_length=11)),
                ('course', models.ManyToManyField(to='pracownicy.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
